#!/bin/sh
SBT_OPTS="-Xms512M -Xmx8G -Xss2M -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024M -Dsbt.log.noformat=true -Djava.library.path=./tmplib"

exec java ${SBT_OPTS} -jar sbt-launch.jar "$@" < /dev/null
